-- DevHUB Marketplace Schema (PostgreSQL / Supabase)
-- Converted from MySQL source files

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    telefone VARCHAR(15),
    senha VARCHAR(255) NOT NULL,
    foto_perfil VARCHAR(255),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_ultimo_acesso TIMESTAMPTZ,
    ativo BOOLEAN DEFAULT TRUE
);


CREATE TABLE IF NOT EXISTS enderecos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo TEXT DEFAULT 'residencial' CHECK (tipo IN ('residencial', 'comercial', 'outro')),
    endereco VARCHAR(255) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(255),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado VARCHAR(2),
    cep VARCHAR(9),
    principal BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS metodos_pagamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo TEXT CHECK (tipo IN ('cartao_credito', 'cartao_debito', 'boleto', 'pix')) NOT NULL,
    titular VARCHAR(255),
    numero_mascado VARCHAR(20),
    mes_validade INTEGER,
    ano_validade INTEGER,
    chave_pix VARCHAR(255),
    padrao BOOLEAN DEFAULT FALSE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    categoria VARCHAR(100),
    preco NUMERIC(10, 2) NOT NULL,
    preco_original NUMERIC(10, 2),
    estoque INTEGER DEFAULT 0,
    imagem_principal VARCHAR(255),
    rating NUMERIC(3, 2) DEFAULT 0,
    quantidade_avaliacoes INTEGER DEFAULT 0,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS carrinho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    produto_id INTEGER NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    preco_unitario NUMERIC(10, 2),
    data_adicao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, produto_id)
);


CREATE TABLE IF NOT EXISTS cupons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) UNIQUE NOT NULL,
    descricao VARCHAR(255),
    tipo TEXT DEFAULT 'percentual' CHECK (tipo IN ('percentual', 'fixo')),
    valor NUMERIC(10, 2) NOT NULL,
    minimo_compra NUMERIC(10, 2),
    quantidade_total INTEGER,
    quantidade_usada INTEGER DEFAULT 0,
    usuario_id INTEGER,
    data_inicio DATE,
    data_fim DATE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS pedidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    endereco_entrega_id INTEGER NOT NULL,
    metodo_pagamento_id INTEGER NOT NULL,
    cupom_id INTEGER,
    status TEXT DEFAULT 'pendente' CHECK (status IN ('pendente', 'processando', 'enviado', 'entregue', 'cancelado', 'devolvido')),
    subtotal NUMERIC(10, 2) NOT NULL,
    desconto NUMERIC(10, 2) DEFAULT 0,
    taxa_entrega NUMERIC(10, 2),
    total NUMERIC(10, 2) NOT NULL,
    numero_rastreio VARCHAR(50),
    data_pedido TIMESTAMPTZ DEFAULT NOW(),
    data_entrega_prevista DATE,
    data_entrega_real DATE,
    data_cancelamento DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (endereco_entrega_id) REFERENCES enderecos(id),
    FOREIGN KEY (metodo_pagamento_id) REFERENCES metodos_pagamento(id),
    FOREIGN KEY (cupom_id) REFERENCES cupons(id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS itens_pedido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL,
    produto_id INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produtos(id)
);


CREATE TABLE IF NOT EXISTS favoritos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    produto_id INTEGER NOT NULL,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, produto_id)
);


CREATE TABLE IF NOT EXISTS wishlist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    produto_id INTEGER NOT NULL,
    alerta_preco BOOLEAN DEFAULT FALSE,
    preco_alerta NUMERIC(10, 2),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, produto_id)
);


CREATE TABLE IF NOT EXISTS avaliacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL,
    produto_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    titulo VARCHAR(255),
    comentario TEXT,
    fotos VARCHAR(500),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produtos(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    UNIQUE (usuario_id, produto_id)
);


CREATE TABLE IF NOT EXISTS notificacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT,
    tipo TEXT DEFAULT 'sistema' CHECK (tipo IN ('pedido', 'promocao', 'oferta', 'sistema')),
    lido BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS mensagens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    pedido_id INTEGER,
    tipo TEXT DEFAULT 'usuario_vendedor' CHECK (tipo IN ('usuario_vendedor', 'suporte')),
    assunto VARCHAR(255),
    mensagem TEXT NOT NULL,
    remetente VARCHAR(50),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS devolucoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    descricao TEXT,
    status TEXT DEFAULT 'solicitada' CHECK (status IN ('solicitada', 'aprovada', 'recusada', 'reembolsada')),
    numero_etiqueta VARCHAR(50),
    data_solicitacao TIMESTAMPTZ DEFAULT NOW(),
    data_resolucao DATE,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS denuncias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    produto_id INTEGER,
    tipo TEXT CHECK (tipo IN ('produto_falso', 'nao_entregue', 'descricao_incorreta', 'outro')) NOT NULL,
    descricao TEXT,
    status TEXT DEFAULT 'aberta' CHECK (status IN ('aberta', 'em_analise', 'resolvida')),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS fornecedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL UNIQUE,
    nome_empresa VARCHAR(255) NOT NULL,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    razao_social VARCHAR(255),
    logo VARCHAR(255),
    descricao TEXT,
    site VARCHAR(255),
    telefone_empresa VARCHAR(15),
    endereco VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(255),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado VARCHAR(2),
    cep VARCHAR(9),
    taxa_comissao NUMERIC(5, 2) DEFAULT 20.00,
    saldo_pendente NUMERIC(12, 2) DEFAULT 0,
    saldo_disponivel NUMERIC(12, 2) DEFAULT 0,
    bancos_permitidos INTEGER DEFAULT 5,
    verificado BOOLEAN DEFAULT FALSE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS softwares (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    nome VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    descricao TEXT,
    descricao_tecnica TEXT,
    categoria VARCHAR(100),
    subcategoria VARCHAR(100),
    tags VARCHAR(500),
    logo VARCHAR(255),
    banner VARCHAR(255),
    screenshots JSONB,
    linguagem_programacao VARCHAR(50),
    so_compativel VARCHAR(255),
    requisitos_minimos TEXT,
    requisitos_recomendados TEXT,
    preco_base NUMERIC(10, 2) NOT NULL,
    rating NUMERIC(3, 2) DEFAULT 0,
    quantidade_avaliacoes INTEGER DEFAULT 0,
    downloads_totais INTEGER DEFAULT 0,
    usuarios_ativos INTEGER DEFAULT 0,
    publicado BOOLEAN DEFAULT FALSE,
    em_destaque BOOLEAN DEFAULT FALSE,
    data_lancamento DATE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_fornecedor ON softwares(fornecedor_id);


CREATE TABLE IF NOT EXISTS planos_preco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    tipo TEXT DEFAULT 'lite' CHECK (tipo IN ('trial', 'lite', 'pro', 'enterprise', 'custom')),
    descricao TEXT,
    preco NUMERIC(10, 2) NOT NULL,
    duracao_dias INTEGER,
    limite_usuarios INTEGER,
    limite_instalacoes INTEGER,
    suporte_incluso BOOLEAN DEFAULT FALSE,
    updates_incluso BOOLEAN DEFAULT TRUE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS midia_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    tipo_midia TEXT CHECK (tipo_midia IN ('logo', 'banner', 'screenshot', 'icon', 'tutorial', 'documento', 'video')) NOT NULL,
    titulo VARCHAR(255),
    descricao TEXT,
    alt_text VARCHAR(500),
    url_midia VARCHAR(500) NOT NULL,
    url_miniatura VARCHAR(500),
    url_cdn VARCHAR(500),
    tipo_arquivo VARCHAR(50),
    tamanho_bytes BIGINT,
    dimensoes_width INTEGER,
    dimensoes_height INTEGER,
    duracao_video INTEGER,
    ordem_exibicao INTEGER,
    visitacoes INTEGER DEFAULT 0,
    downlod INTEGER DEFAULT 0,
    principal BOOLEAN DEFAULT FALSE,
    ativo BOOLEAN DEFAULT TRUE,
    data_upload TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_software_tipo ON midia_software(software_id, tipo_midia);


CREATE TABLE IF NOT EXISTS caracteristicas_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    nome_feature VARCHAR(255) NOT NULL,
    descricao TEXT,
    icone VARCHAR(255),
    categoria_feature VARCHAR(100),
    disponivel_planos JSONB,
    ordem INTEGER,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS requisitos_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    so VARCHAR(100),
    versao_minima VARCHAR(50),
    versao_recomendada VARCHAR(50),
    memoria_minima_gb NUMERIC(3, 1),
    memoria_recomendada_gb NUMERIC(3, 1),
    espaco_disco_gb INTEGER,
    processador_minimo VARCHAR(255),
    parametros_adicionais TEXT,
    obrigatorio BOOLEAN DEFAULT TRUE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS versoes_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    numero_versao VARCHAR(50) NOT NULL,
    changelog TEXT,
    features_novas TEXT,
    bugs_corrigidos TEXT,
    melhorias_performance TEXT,
    breaking_changes TEXT,
    data_lancamento DATE,
    arquivo_url VARCHAR(255),
    arquivo_windows VARCHAR(255),
    arquivo_mac VARCHAR(255),
    arquivo_linux VARCHAR(255),
    tamanho_windows_mb INTEGER,
    tamanho_mac_mb INTEGER,
    tamanho_linux_mb INTEGER,
    hash_windows VARCHAR(255),
    hash_mac VARCHAR(255),
    hash_linux VARCHAR(255),
    versao_atual BOOLEAN DEFAULT FALSE,
    versao_suportada BOOLEAN DEFAULT TRUE,
    versao_segura BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id, numero_versao)
);
CREATE INDEX IF NOT EXISTS idx_versao_atual ON versoes_software(software_id, versao_atual);


CREATE TABLE IF NOT EXISTS licencas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    plano_id INTEGER NOT NULL,
    chave_licenca VARCHAR(255) UNIQUE NOT NULL,
    chave_validacao VARCHAR(255),
    status TEXT DEFAULT 'ativa' CHECK (status IN ('ativa', 'expirada', 'cancelada', 'suspensa', 'em_trial')),
    tipo_licenca TEXT DEFAULT 'pessoal' CHECK (tipo_licenca IN ('pessoal', 'comercial', 'educacional', 'governo')),
    data_compra TIMESTAMPTZ DEFAULT NOW(),
    data_expiracao DATE,
    data_renovacao_proxima DATE,
    renovacao_automatica BOOLEAN DEFAULT TRUE,
    downloads_restantes INTEGER DEFAULT -1,
    instalacoes_restantes INTEGER DEFAULT -1,
    instalacoes_ativas INTEGER DEFAULT 0,
    ultimo_acesso DATE,
    ultima_versao_acessada VARCHAR(50),
    data_cancelamento DATE,
    motivo_cancelamento VARCHAR(255),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (plano_id) REFERENCES planos_preco(id)
);
CREATE INDEX IF NOT EXISTS idx_usuario_software ON licencas(usuario_id, software_id);
CREATE INDEX IF NOT EXISTS idx_chave_licenca ON licencas(chave_licenca);
CREATE INDEX IF NOT EXISTS idx_status ON licencas(status);


CREATE TABLE IF NOT EXISTS vendas_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    pedido_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    plano_id INTEGER,
    licenca_id INTEGER,
    versao_software_id INTEGER,
    usuario_id INTEGER,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    desconto_cupom NUMERIC(10, 2) DEFAULT 0,
    comissao_marketplace NUMERIC(10, 2),
    valor_liquido NUMERIC(10, 2),
    imposto_retido NUMERIC(10, 2) DEFAULT 0,
    status_pagamento TEXT DEFAULT 'pendente' CHECK (status_pagamento IN ('pendente', 'processando', 'pago', 'retido', 'falha', 'reembolsado')),
    banco_destino VARCHAR(50),
    chave_pix_destino VARCHAR(255),
    tipo_transacao TEXT DEFAULT 'venda' CHECK (tipo_transacao IN ('venda', 'reembolso', 'ajuste')),
    data_venda TIMESTAMPTZ DEFAULT NOW(),
    data_pagamento DATE,
    observacoes TEXT,
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (plano_id) REFERENCES planos_preco(id),
    FOREIGN KEY (licenca_id) REFERENCES licencas(id),
    FOREIGN KEY (versao_software_id) REFERENCES versoes_software(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_fornecedor ON vendas_software(fornecedor_id);
CREATE INDEX IF NOT EXISTS idx_data_venda ON vendas_software(data_venda);
CREATE INDEX IF NOT EXISTS idx_status_pagamento ON vendas_software(status_pagamento);


CREATE TABLE IF NOT EXISTS tickets_suporte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    fornecedor_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    licenca_id INTEGER,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
    status TEXT DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_progresso', 'aguardando_cliente', 'resolvido', 'fechado', 'reaberto')),
    categoria VARCHAR(100),
    tags VARCHAR(500),
    tempo_resposta_horas INTEGER,
    solucao_encontrada BOOLEAN DEFAULT FALSE,
    satisfacao_cliente INTEGER,
    respostas INTEGER DEFAULT 0,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    data_fechamento DATE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (licenca_id) REFERENCES licencas(id)
);
CREATE INDEX IF NOT EXISTS idx_status ON tickets_suporte(status);
CREATE INDEX IF NOT EXISTS idx_usuario ON tickets_suporte(usuario_id);
CREATE INDEX IF NOT EXISTS idx_software ON tickets_suporte(software_id);


CREATE TABLE IF NOT EXISTS respostas_suporte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    usuario_id INTEGER,
    fornecedor_id INTEGER,
    tipo_resposta TEXT DEFAULT 'usuario' CHECK (tipo_resposta IN ('usuario', 'fornecedor', 'suporte_marketplace')),
    mensagem TEXT NOT NULL,
    tempo_resposta_minutos INTEGER,
    tempo_resolucao_minutos INTEGER,
    anexos JSONB,
    lido BOOLEAN DEFAULT FALSE,
    marcado_solucao BOOLEAN DEFAULT FALSE,
    pontuacao_util INTEGER DEFAULT 0,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (ticket_id) REFERENCES tickets_suporte(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id)
);
CREATE INDEX IF NOT EXISTS idx_ticket ON respostas_suporte(ticket_id);


CREATE TABLE IF NOT EXISTS cupons_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    software_id INTEGER,
    codigo VARCHAR(50) UNIQUE NOT NULL,
    descricao VARCHAR(255),
    tipo TEXT DEFAULT 'percentual' CHECK (tipo IN ('percentual', 'fixo')),
    valor NUMERIC(10, 2) NOT NULL,
    minimo_compra NUMERIC(10, 2),
    quantidade_total INTEGER,
    quantidade_usada INTEGER DEFAULT 0,
    limite_por_usuario INTEGER DEFAULT 1,
    categoria_aplicavel VARCHAR(100),
    data_inicio DATE,
    data_fim DATE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_codigo ON cupons_software(codigo);
CREATE INDEX IF NOT EXISTS idx_ativo ON cupons_software(ativo);


CREATE TABLE IF NOT EXISTS equipe_desenvolvimento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    papel TEXT DEFAULT 'developer' CHECK (papel IN ('owner', 'developer', 'tester', 'manager', 'analyst', 'designer')),
    permissoes JSONB,
    software_restrito_id INTEGER,
    data_adicao TIMESTAMPTZ DEFAULT NOW(),
    ativo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (software_restrito_id) REFERENCES softwares(id) ON DELETE SET NULL,
    UNIQUE (fornecedor_id, usuario_id)
);
CREATE INDEX IF NOT EXISTS idx_papel ON equipe_desenvolvimento(papel);


CREATE TABLE IF NOT EXISTS integracao_git (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    tipo_repo TEXT CHECK (tipo_repo IN ('github', 'gitlab', 'bitbucket', 'gitea')) NOT NULL,
    url_repositorio VARCHAR(500),
    token_acesso VARCHAR(500),
    owner_repo VARCHAR(255),
    branch_principal VARCHAR(100) DEFAULT 'main',
    webhook_url VARCHAR(500),
    webhook_secret VARCHAR(500),
    webhook_ativo BOOLEAN DEFAULT TRUE,
    build_automatico BOOLEAN DEFAULT TRUE,
    teste_automatico BOOLEAN DEFAULT TRUE,
    deploy_automatico BOOLEAN DEFAULT FALSE,
    ultima_sincronizacao TIMESTAMPTZ,
    proxima_sincronizacao TIMESTAMPTZ,
    commits_total INTEGER DEFAULT 0,
    contributors INTEGER DEFAULT 0,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id, tipo_repo)
);


CREATE TABLE IF NOT EXISTS estatisticas_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    data_relatorio DATE,
    downloads_dia INTEGER DEFAULT 0,
    downloads_total INTEGER DEFAULT 0,
    vendas_dia INTEGER DEFAULT 0,
    vendas_total INTEGER DEFAULT 0,
    receita_dia NUMERIC(12, 2) DEFAULT 0,
    receita_total NUMERIC(12, 2) DEFAULT 0,
    usuarios_novos_dia INTEGER DEFAULT 0,
    usuarios_ativos_total INTEGER DEFAULT 0,
    usuarios_inativos INTEGER DEFAULT 0,
    rating_medio NUMERIC(3, 2) DEFAULT 0,
    taxa_retencao NUMERIC(5, 2),
    taxa_churn NUMERIC(5, 2),
    tempo_uso_medio_horas INTEGER,
    feature_mais_usadas JSONB,
    versao_mais_usada VARCHAR(50),
    so_mais_usado VARCHAR(100),
    pais_mais_vendas VARCHAR(100),
    UNIQUE (software_id, data_relatorio),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_data ON estatisticas_software(data_relatorio);


CREATE TABLE IF NOT EXISTS telemetria_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licenca_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    evento_tipo VARCHAR(100),
    sessao_id VARCHAR(255),
    detalhes JSONB,
    versao_software VARCHAR(50),
    build_numero INTEGER,
    so_usuario VARCHAR(50),
    versao_so VARCHAR(50),
    arquitetura VARCHAR(20),
    navegador VARCHAR(100),
    resolucao_tela VARCHAR(20),
    ip_usuario VARCHAR(50),
    pais VARCHAR(100),
    cidade VARCHAR(100),
    locacao_lat NUMERIC(10, 8),
    locacao_lng NUMERIC(11, 8),
    duracao_sessao_segundos INTEGER,
    paginas_visitadas INTEGER,
    tempo_inatividade_segundos INTEGER,
    data_evento TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (licenca_id) REFERENCES licencas(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);
CREATE INDEX IF NOT EXISTS idx_licenca_data ON telemetria_software(licenca_id, data_evento);
CREATE INDEX IF NOT EXISTS idx_evento_tipo ON telemetria_software(evento_tipo);
CREATE INDEX IF NOT EXISTS idx_sessao ON telemetria_software(sessao_id);


CREATE TABLE IF NOT EXISTS feature_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    usuario_id INTEGER,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    categoria VARCHAR(100),
    votos INTEGER DEFAULT 1,
    comentarios INTEGER DEFAULT 0,
    status TEXT DEFAULT 'novo' CHECK (status IN ('novo', 'considerando', 'planejado', 'em_desenvolvimento', 'completo', 'rejeitado', 'duplicado')),
    data_implementacao DATE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_status ON feature_requests(status);
CREATE INDEX IF NOT EXISTS idx_votos ON feature_requests(votos);


CREATE TABLE IF NOT EXISTS webhooks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    url_webhook VARCHAR(500) NOT NULL,
    eventos JSONB,
    headers_customizados JSONB,
    metodo_http VARCHAR(10) DEFAULT 'POST',
    timeout_segundos INTEGER DEFAULT 30,
    tentativas_maximas INTEGER DEFAULT 5,
    tentativas_falhas INTEGER DEFAULT 0,
    ultima_tentativa TIMESTAMPTZ,
    proxima_tentativa TIMESTAMPTZ,
    status_ultimo_envio VARCHAR(3),
    resposta_ultimo_envio TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS auditoria_softwares (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    usuario_id INTEGER,
    software_id INTEGER,
    tabela_alvo VARCHAR(100),
    tipo_acao TEXT DEFAULT 'update' CHECK (tipo_acao IN ('insert', 'update', 'delete', 'login', 'export', 'publicacao', 'cancela')),
    descricao TEXT,
    dados_anterior JSONB,
    dados_novo JSONB,
    endereco_ip VARCHAR(50),
    user_agent VARCHAR(500),
    data_acao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);
CREATE INDEX IF NOT EXISTS idx_fornecedor_data ON auditoria_softwares(fornecedor_id, data_acao);
CREATE INDEX IF NOT EXISTS idx_tipo_acao ON auditoria_softwares(tipo_acao);


CREATE TABLE IF NOT EXISTS software_categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    ordem INTEGER DEFAULT 1,
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id, categoria)
);
CREATE INDEX IF NOT EXISTS idx_categoria ON software_categorias(categoria);


CREATE TABLE IF NOT EXISTS software_tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    tag VARCHAR(50) NOT NULL,
    frequencia INTEGER DEFAULT 1,
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id, tag)
);
CREATE INDEX IF NOT EXISTS idx_tag ON software_tags(tag);


CREATE TABLE IF NOT EXISTS plano_caracteristicas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id INTEGER NOT NULL,
    caracteristica_id INTEGER NOT NULL,
    FOREIGN KEY (plano_id) REFERENCES planos_preco(id) ON DELETE CASCADE,
    FOREIGN KEY (caracteristica_id) REFERENCES caracteristicas_software(id) ON DELETE CASCADE,
    UNIQUE (plano_id, caracteristica_id)
);


CREATE TABLE IF NOT EXISTS usuario_voto_feature (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    tipo_voto TEXT DEFAULT 'upvote' CHECK (tipo_voto IN ('upvote', 'downvote', 'neutro')),
    data_voto TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (feature_id) REFERENCES feature_requests(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (feature_id, usuario_id)
);
CREATE INDEX IF NOT EXISTS idx_usuario ON usuario_voto_feature(usuario_id);


CREATE TABLE IF NOT EXISTS avaliacao_utilidade (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    util BOOLEAN,
    data_voto TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (avaliacao_id, usuario_id)
);


CREATE TABLE IF NOT EXISTS softwares_relacionados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_a INTEGER NOT NULL,
    software_b INTEGER NOT NULL,
    tipo_relacao TEXT DEFAULT 'similar' CHECK (tipo_relacao IN ('similar', 'complementar', 'competidor')),
    score_relevancia NUMERIC(3, 2),
    FOREIGN KEY (software_a) REFERENCES softwares(id) ON DELETE CASCADE,
    FOREIGN KEY (software_b) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_a, software_b)
);


CREATE TABLE IF NOT EXISTS bundles_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    preco_bundle NUMERIC(10, 2),
    desconto_percentual NUMERIC(5, 2),
    economia_total NUMERIC(10, 2),
    criado_por INTEGER NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (criado_por) REFERENCES fornecedores(id)
);


CREATE TABLE IF NOT EXISTS bundle_itens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    preco_no_bundle NUMERIC(10, 2),
    ordem INTEGER,
    FOREIGN KEY (bundle_id) REFERENCES bundles_software(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    UNIQUE (bundle_id, software_id)
);


CREATE TABLE IF NOT EXISTS extensoes_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_host_id INTEGER NOT NULL,
    software_extensao_id INTEGER NOT NULL,
    descricao_integracao TEXT,
    versao_minima_host VARCHAR(50),
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_host_id) REFERENCES softwares(id) ON DELETE CASCADE,
    FOREIGN KEY (software_extensao_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_host_id, software_extensao_id)
);


CREATE TABLE IF NOT EXISTS configuracoes_marketplace (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave_config VARCHAR(100) UNIQUE NOT NULL,
    valor_config TEXT,
    tipo TEXT DEFAULT 'string' CHECK (tipo IN ('string', 'number', 'BOOLEAN', 'JSONB')),
    descricao VARCHAR(500),
    editavel_admin BOOLEAN DEFAULT TRUE,
    data_atualizacao TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS configuracoes_fornecedor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    chave_config VARCHAR(100),
    valor_config TEXT,
    tipo TEXT DEFAULT 'string' CHECK (tipo IN ('string', 'number', 'BOOLEAN', 'JSONB')),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id) ON DELETE CASCADE,
    UNIQUE (fornecedor_id, chave_config)
);


CREATE TABLE IF NOT EXISTS configuracoes_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tema VARCHAR(50) DEFAULT 'light',
    idioma VARCHAR(10) DEFAULT 'pt-BR',
    moeda_preferida VARCHAR(3) DEFAULT 'BRL',
    pais VARCHAR(100),
    tipo_usuario TEXT DEFAULT 'cliente' CHECK (tipo_usuario IN ('cliente', 'fornecedor', 'admin')),
    documento_verificado BOOLEAN DEFAULT FALSE,
    notificacoes_email BOOLEAN DEFAULT TRUE,
    notificacoes_push BOOLEAN DEFAULT TRUE,
    privacidade_profile TEXT DEFAULT 'publica' CHECK (privacidade_profile IN ('publica', 'amigos', 'privada')),
    dois_fator_ativado BOOLEAN DEFAULT FALSE,
    data_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id)
);


CREATE TABLE IF NOT EXISTS configuracoes_notificacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_notificacao VARCHAR(100),
    email BOOLEAN DEFAULT TRUE,
    push BOOLEAN DEFAULT TRUE,
    sms BOOLEAN DEFAULT FALSE,
    inapp BOOLEAN DEFAULT TRUE,
    data_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, tipo_notificacao)
);


CREATE TABLE IF NOT EXISTS sessoes_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    token_sessao VARCHAR(255) UNIQUE NOT NULL,
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_expiracao TIMESTAMPTZ,
    ultima_atividade TIMESTAMPTZ DEFAULT NOW(),
    ativo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_token ON sessoes_usuario(token_sessao);
CREATE INDEX IF NOT EXISTS idx_usuario_id ON sessoes_usuario(usuario_id);


CREATE TABLE IF NOT EXISTS tentativas_login_falhas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    ip_address VARCHAR(50),
    tentativa_numero INTEGER DEFAULT 1,
    motivo VARCHAR(255),
    data_tentativa TIMESTAMPTZ DEFAULT NOW(),
    bloqueado_ate TIMESTAMPTZ,
    UNIQUE (email, ip_address)
);
CREATE INDEX IF NOT EXISTS idx_ip ON tentativas_login_falhas(ip_address);
CREATE INDEX IF NOT EXISTS idx_email ON tentativas_login_falhas(email);


CREATE TABLE IF NOT EXISTS logs_seguranca (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    tipo_evento TEXT CHECK (tipo_evento IN ('login', 'logout', 'mudanca_senha', 'mudanca_email', 'falha_login', 'acesso_negado', 'dados_exportados', 'dados_deletados')) NOT NULL,
    descricao TEXT,
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    resultado TEXT DEFAULT 'sucesso' CHECK (resultado IN ('sucesso', 'falha', 'alert')),
    data_evento TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_usuario_tipo ON logs_seguranca(usuario_id, tipo_evento);
CREATE INDEX IF NOT EXISTS idx_data ON logs_seguranca(data_evento);


CREATE TABLE IF NOT EXISTS chaves_api (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    chave_publica VARCHAR(255) UNIQUE NOT NULL,
    chave_privada VARCHAR(255) UNIQUE NOT NULL,
    nome_chave VARCHAR(100),
    escopo JSONB,
    limite_requisicoes_dia INTEGER,
    requisicoes_hoje INTEGER DEFAULT 0,
    data_reset_contador DATE,
    ativa BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    ultima_utilizacao TIMESTAMPTZ,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chave_publica ON chaves_api(chave_publica);


CREATE TABLE IF NOT EXISTS autenticacao_2fa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_2fa TEXT CHECK (tipo_2fa IN ('totp', 'email', 'sms')) NOT NULL,
    secret_totp VARCHAR(255),
    telefone_sms VARCHAR(15),
    backup_codes JSONB,
    ativo BOOLEAN DEFAULT FALSE,
    data_ativacao TIMESTAMPTZ,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, tipo_2fa)
);


CREATE TABLE IF NOT EXISTS ips_bloqueados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(50) UNIQUE NOT NULL,
    motivo VARCHAR(255),
    bloqueado_por INTEGER,
    data_bloqueio TIMESTAMPTZ DEFAULT NOW(),
    data_desbloqueio TIMESTAMPTZ,
    permanente BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (bloqueado_por) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS historico_pagamento_fornecedor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    periodo_inicio DATE,
    periodo_fim DATE,
    cantidad_vendas INTEGER,
    valor_bruto NUMERIC(12, 2),
    comissao_marketplace NUMERIC(12, 2),
    impostos_retidos NUMERIC(12, 2),
    ajustes NUMERIC(12, 2),
    valor_liquido NUMERIC(12, 2),
    status_pagamento TEXT DEFAULT 'processando' CHECK (status_pagamento IN ('processando', 'agendado', 'pago', 'falha', 'retido')),
    data_programada_pagamento DATE,
    data_pagamento_efetivo DATE,
    meio_pagamento VARCHAR(50),
    numero_comprovante VARCHAR(100),
    observacoes TEXT,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id)
);
CREATE INDEX IF NOT EXISTS idx_fornecedor_periodo ON historico_pagamento_fornecedor(fornecedor_id, periodo_inicio);


CREATE TABLE IF NOT EXISTS taxas_fornecedor_customizado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    categoria_software VARCHAR(100),
    taxa_comissao NUMERIC(5, 2),
    taxa_minima NUMERIC(10, 2),
    motivo_customizacao VARCHAR(255),
    data_inicio DATE,
    data_fim DATE,
    aprovado_admin INTEGER,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (aprovado_admin) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS ciclo_pagamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    tipo_ciclo TEXT DEFAULT 'mensal' CHECK (tipo_ciclo IN ('diario', 'semanal', 'quinzenal', 'mensal')),
    dia_pagamento INTEGER,
    mes_pagamento INTEGER,
    valor_minimo_liberacao NUMERIC(12, 2),
    proxima_data_pagamento DATE,
    ultima_data_pagamento DATE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    UNIQUE (fornecedor_id)
);


CREATE TABLE IF NOT EXISTS retencao_pagamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    valor_retido NUMERIC(12, 2),
    motivo_retencao VARCHAR(255),
    descricao TEXT,
    data_retencao TIMESTAMPTZ DEFAULT NOW(),
    data_liberacao DATE,
    status TEXT DEFAULT 'retido' CHECK (status IN ('retido', 'liberado_parcial', 'liberado_total', 'cancelado')),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id)
);
CREATE INDEX IF NOT EXISTS idx_status ON retencao_pagamento(status);


CREATE TABLE IF NOT EXISTS reembolsos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    descricao TEXT,
    valor_reembolso NUMERIC(10, 2),
    metodo_reembolso VARCHAR(50),
    status TEXT DEFAULT 'solicitado' CHECK (status IN ('solicitado', 'aprovado', 'processando', 'concluido', 'rejeitado')),
    data_solicitacao TIMESTAMPTZ DEFAULT NOW(),
    data_processamento DATE,
    data_conclusao DATE,
    comprovante_transacao VARCHAR(255),
    FOREIGN KEY (venda_id) REFERENCES vendas_software(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_status ON reembolsos(status);


CREATE TABLE IF NOT EXISTS boletos_emitidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    numero_boleto VARCHAR(50) UNIQUE NOT NULL,
    valor_boleto NUMERIC(12, 2),
    data_vencimento DATE,
    data_emissao TIMESTAMPTZ DEFAULT NOW(),
    banco_emissor VARCHAR(50),
    url_boleto VARCHAR(500),
    status TEXT DEFAULT 'emitido' CHECK (status IN ('emitido', 'lido', 'pago', 'vencido', 'cancelado')),
    data_pagamento DATE,
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id)
);
CREATE INDEX IF NOT EXISTS idx_status ON boletos_emitidos(status);


CREATE TABLE IF NOT EXISTS campanhas_email (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criada_por INTEGER NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    assunto_email VARCHAR(255),
    corpo_email TEXT,
    tipo_campanha TEXT DEFAULT 'newsletter' CHECK (tipo_campanha IN ('promocao', 'newsletter', 'transacional', 'reengajamento', 'onboarding')),
    segmento_alvo VARCHAR(100),
    data_agendada DATE,
    data_envio TIMESTAMPTZ,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'rascunho' CHECK (status IN ('rascunho', 'agendada', 'enviando', 'enviada', 'cancelada')),
    total_destinatarios INTEGER,
    enviados INTEGER DEFAULT 0,
    abertos INTEGER DEFAULT 0,
    cliques INTEGER DEFAULT 0,
    taxa_entrega NUMERIC(5, 2),
    taxa_abertura NUMERIC(5, 2),
    taxa_clique NUMERIC(5, 2),
    FOREIGN KEY (criada_por) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS emails_agendados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    destinatario_email VARCHAR(255),
    assunto VARCHAR(255),
    corpo TEXT,
    tipo_email VARCHAR(50),
    data_agendada TIMESTAMPTZ,
    data_envio TIMESTAMPTZ,
    status TEXT DEFAULT 'agendado' CHECK (status IN ('agendado', 'enviado', 'falha', 'cancelado')),
    tentativas INTEGER DEFAULT 0,
    proxima_tentativa TIMESTAMPTZ,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS templates_email (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_template VARCHAR(100) UNIQUE NOT NULL,
    categoria VARCHAR(50),
    assunto_padrao VARCHAR(255),
    corpo_template TEXT,
    variaveis_suportadas JSONB,
    criado_por INTEGER,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (criado_por) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS historico_envio_email (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    email_destinatario VARCHAR(255),
    campanha_id INTEGER,
    assunto VARCHAR(255),
    tipo_email VARCHAR(50),
    status_envio TEXT DEFAULT 'enviado' CHECK (status_envio IN ('enviado', 'falha', 'bounce', 'spam')),
    motivo_falha VARCHAR(255),
    data_envio TIMESTAMPTZ DEFAULT NOW(),
    data_abertura TIMESTAMPTZ,
    links_clicados INTEGER DEFAULT 0,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (campanha_id) REFERENCES campanhas_email(id)
);
CREATE INDEX IF NOT EXISTS idx_data_envio ON historico_envio_email(data_envio);


CREATE TABLE IF NOT EXISTS unsubscribe_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    email VARCHAR(255),
    tipo_email VARCHAR(50),
    data_unsubscribe TIMESTAMPTZ DEFAULT NOW(),
    motivo VARCHAR(255),
    resubscricao_permitida BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
    UNIQUE (email, tipo_email)
);


CREATE TABLE IF NOT EXISTS notificacoes_push (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    titulo VARCHAR(255),
    mensagem TEXT,
    icone VARCHAR(255),
    url_acao VARCHAR(500),
    tipo_notificacao VARCHAR(50),
    lida BOOLEAN DEFAULT FALSE,
    clicada BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_leitura TIMESTAMPTZ,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_usuario_lida ON notificacoes_push(usuario_id, lida);


CREATE TABLE IF NOT EXISTS funil_conversao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_relatorio DATE,
    etapa_funil VARCHAR(100),
    quantidade_usuarios INTEGER,
    quantidade_convertidos INTEGER,
    taxa_conversao NUMERIC(5, 2),
    software_id INTEGER,
    categoria_software VARCHAR(100),
    UNIQUE (data_relatorio, etapa_funil, software_id),
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);


CREATE TABLE IF NOT EXISTS analise_busca (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termo_busca VARCHAR(255),
    quantidade_buscas INTEGER DEFAULT 1,
    quantidade_resultados INTEGER,
    resultados_clicados INTEGER DEFAULT 0,
    taxa_conversao_post_busca NUMERIC(5, 2),
    categoria_maior_relevancia VARCHAR(100),
    data_ultima_busca TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_termo ON analise_busca(termo_busca);


CREATE TABLE IF NOT EXISTS analise_abandono_carrinho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    carrinho_id INTEGER NOT NULL,
    valor_total NUMERIC(10, 2),
    quantidade_itens INTEGER,
    motivo_abandono VARCHAR(255),
    tempo_carrinho_minutos INTEGER,
    recuperado BOOLEAN DEFAULT FALSE,
    data_abandono TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_usuario_data ON analise_abandono_carrinho(usuario_id, data_abandono);


CREATE TABLE IF NOT EXISTS analise_churn_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    dias_inatividade INTEGER,
    ultima_atividade_data DATE,
    risco_churn TEXT DEFAULT 'baixo' CHECK (risco_churn IN ('baixo', 'medio', 'alto', 'critico')),
    valor_vida_usuario NUMERIC(12, 2),
    motivo_suspeito_churn VARCHAR(255),
    data_analise TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    UNIQUE (usuario_id, data_analise)
);


CREATE TABLE IF NOT EXISTS heatmap_aplicacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    sessao_id VARCHAR(255),
    pagina_url VARCHAR(500),
    posicao_x INTEGER,
    posicao_y INTEGER,
    tipo_evento TEXT DEFAULT 'click' CHECK (tipo_evento IN ('click', 'scroll', 'hover', 'keystroke')),
    elemento_html VARCHAR(255),
    duracao_segundos INTEGER,
    TIMESTAMPTZ TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_sessao ON heatmap_aplicacao(sessao_id);


CREATE TABLE IF NOT EXISTS performance_servidor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpu_percentual NUMERIC(5, 2),
    memoria_usada_gb NUMERIC(5, 2),
    memoria_total_gb NUMERIC(5, 2),
    disco_usado_gb NUMERIC(10, 2),
    disco_total_gb NUMERIC(10, 2),
    latencia_media_ms INTEGER,
    requisicoes_por_segundo INTEGER,
    taxa_erro INTEGER DEFAULT 0,
    status_servico TEXT DEFAULT 'ok' CHECK (status_servico IN ('ok', 'degradado', 'offline')),
    TIMESTAMPTZ TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_timestamp ON performance_servidor(timestamp);


CREATE TABLE IF NOT EXISTS faq_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    pergunta VARCHAR(500) NOT NULL,
    resposta TEXT NOT NULL,
    categoria_faq VARCHAR(100),
    visualizacoes INTEGER DEFAULT 0,
    util INTEGER DEFAULT 0,
    nao_util INTEGER DEFAULT 0,
    ordem INTEGER,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS artigos_conhecimento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) UNIQUE NOT NULL,
    descricao TEXT,
    conteudo TEXT,
    categoria VARCHAR(100),
    tags VARCHAR(500),
    autor_id INTEGER,
    visualizacoes INTEGER DEFAULT 0,
    util INTEGER DEFAULT 0,
    nao_util INTEGER DEFAULT 0,
    ativo BOOLEAN DEFAULT TRUE,
    data_publicacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (autor_id) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS video_tutorials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    titulo VARCHAR(255),
    descricao TEXT,
    url_video VARCHAR(500),
    duracao_segundos INTEGER,
    visualizacoes INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    categoria_tutorial VARCHAR(100),
    ordem INTEGER,
    ativo BOOLEAN DEFAULT TRUE,
    data_upload TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS guias_instalacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    sistema_operacional VARCHAR(50),
    versao_so VARCHAR(50),
    passo_a_passo TEXT,
    requisitos TEXT,
    solucao_problemas TEXT,
    screenshots JSONB,
    tempo_instalacao_minutos INTEGER,
    dificuldade TEXT DEFAULT 'media' CHECK (dificuldade IN ('facil', 'media', 'dificil')),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id, sistema_operacional)
);


CREATE TABLE IF NOT EXISTS documentacao_api (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    endpoint VARCHAR(500),
    metodo_http VARCHAR(10),
    descricao_endpoint TEXT,
    parametros JSONB,
    exemplo_requisicao TEXT,
    exemplo_resposta TEXT,
    codigo_resposta INTEGER,
    rate_limit INTEGER,
    versao_api VARCHAR(50),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS moderacao_conteudo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL,
    status_moderacao TEXT DEFAULT 'pendente' CHECK (status_moderacao IN ('pendente', 'aprovada', 'rejeitada', 'editada')),
    motivo_rejeicao VARCHAR(255),
    moderador_id INTEGER,
    comentario_moderador TEXT,
    data_moderacao TIMESTAMPTZ,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON DELETE CASCADE,
    FOREIGN KEY (moderador_id) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS denuncia_avaliacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    tipo_denuncia TEXT CHECK (tipo_denuncia IN ('falsa', 'inconveniente', 'spam', 'ofensiva')) NOT NULL,
    descricao TEXT,
    status TEXT DEFAULT 'aberta' CHECK (status IN ('aberta', 'em_analise', 'resolvida', 'descartada')),
    moderador_id INTEGER,
    analise TEXT,
    data_denuncia TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (moderador_id) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS resposta_avaliacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL,
    fornecedor_id INTEGER NOT NULL,
    resposta TEXT NOT NULL,
    curtidas INTEGER DEFAULT 0,
    data_resposta TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON DELETE CASCADE,
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    UNIQUE (avaliacao_id)
);


CREATE TABLE IF NOT EXISTS politicas_marketplace (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_politica TEXT CHECK (tipo_politica IN ('termos_servico', 'privacidade', 'cookies', 'devolucao', 'intelectual')) NOT NULL,
    titulo VARCHAR(255),
    conteudo TEXT,
    versao VARCHAR(10),
    data_vigencia DATE,
    data_proxima_atualizacao DATE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS aceite_usuario_politicas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    politica_id INTEGER NOT NULL,
    versao_aceita VARCHAR(10),
    data_aceite TIMESTAMPTZ DEFAULT NOW(),
    ip_aceite VARCHAR(50),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (politica_id) REFERENCES politicas_marketplace(id),
    UNIQUE (usuario_id, politica_id)
);


CREATE TABLE IF NOT EXISTS dados_lgpd_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_solicitacao TEXT CHECK (tipo_solicitacao IN ('anonimizacao', 'delecao', 'portabilidade')) NOT NULL,
    descricao TEXT,
    status TEXT DEFAULT 'solicitado' CHECK (status IN ('solicitado', 'processando', 'concluido', 'cancelado')),
    data_solicitacao TIMESTAMPTZ DEFAULT NOW(),
    data_conclusao DATE,
    detalhes_processamento TEXT,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, tipo_solicitacao)
);


CREATE TABLE IF NOT EXISTS consentimento_privacidade (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_dado TEXT CHECK (tipo_dado IN ('marketing', 'analiticos', 'cookies', 'compartilhamento')) NOT NULL,
    consentimento BOOLEAN,
    data_consentimento TIMESTAMPTZ DEFAULT NOW(),
    ip_consentimento VARCHAR(50),
    fonte_consentimento VARCHAR(100),
    versao_politica VARCHAR(10),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, tipo_dado)
);


CREATE TABLE IF NOT EXISTS dados_backup_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_backup VARCHAR(50),
    dados_json TEXT,
    tamanho_bytes BIGINT,
    formato_arquivo VARCHAR(20),
    data_backup TIMESTAMPTZ DEFAULT NOW(),
    data_expiracao TIMESTAMPTZ,
    acessado BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS afiliados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    comissao_percentual NUMERIC(5, 2),
    status_afiliado TEXT DEFAULT 'ativo' CHECK (status_afiliado IN ('ativo', 'inativo', 'suspenso', 'rejeitado')),
    site_afiliado VARCHAR(500),
    metodos_promocao JSONB,
    documento_verificado BOOLEAN DEFAULT FALSE,
    dados_bancarios_verificado BOOLEAN DEFAULT FALSE,
    data_cadastro TIMESTAMPTZ DEFAULT NOW(),
    total_vendas_geradas NUMERIC(12, 2) DEFAULT 0,
    total_comissao NUMERIC(12, 2) DEFAULT 0,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id)
);


CREATE TABLE IF NOT EXISTS rastreamento_afiliado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afiliado_id INTEGER NOT NULL,
    link_afiliado VARCHAR(500),
    software_id INTEGER,
    cliques INTEGER DEFAULT 0,
    conversoes INTEGER DEFAULT 0,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    ultima_clique TIMESTAMPTZ,
    FOREIGN KEY (afiliado_id) REFERENCES afiliados(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);


CREATE TABLE IF NOT EXISTS comissao_afiliado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afiliado_id INTEGER NOT NULL,
    venda_id INTEGER NOT NULL,
    software_id INTEGER,
    valor_venda NUMERIC(10, 2),
    percentual_comissao NUMERIC(5, 2),
    valor_comissao NUMERIC(10, 2),
    status_comissao TEXT DEFAULT 'pendente' CHECK (status_comissao IN ('pendente', 'processando', 'paga', 'retida')),
    data_venda TIMESTAMPTZ DEFAULT NOW(),
    data_pagamento DATE,
    FOREIGN KEY (afiliado_id) REFERENCES afiliados(id),
    FOREIGN KEY (venda_id) REFERENCES vendas_software(id),
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);


CREATE TABLE IF NOT EXISTS pagamento_afiliado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afiliado_id INTEGER NOT NULL,
    valor_total NUMERIC(12, 2),
    quantidade_comissoes INTEGER,
    periodo_inicio DATE,
    periodo_fim DATE,
    status_pagamento TEXT DEFAULT 'processando' CHECK (status_pagamento IN ('processando', 'agendado', 'pago', 'falha')),
    data_pagamento DATE,
    metodo_pagamento VARCHAR(50),
    comprovante_transacao VARCHAR(255),
    FOREIGN KEY (afiliado_id) REFERENCES afiliados(id)
);
CREATE INDEX IF NOT EXISTS idx_status ON pagamento_afiliado(status_pagamento);


CREATE TABLE IF NOT EXISTS usuario_pontos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    pontos_totais INTEGER DEFAULT 0,
    pontos_disponiveis INTEGER DEFAULT 0,
    historico_pontos JSONB,
    data_ultima_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id)
);


CREATE TABLE IF NOT EXISTS usuario_badges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    nome_badge VARCHAR(100),
    descricao_badge TEXT,
    icone_badge VARCHAR(255),
    data_obtencao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, nome_badge)
);


CREATE TABLE IF NOT EXISTS usuario_achievements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    nome_achievement VARCHAR(100),
    descricao VARCHAR(500),
    icone_achievement VARCHAR(255),
    progresso_atual INTEGER DEFAULT 0,
    progresso_total INTEGER,
    desbloqueado BOOLEAN DEFAULT FALSE,
    data_desbloqueio TIMESTAMPTZ,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS usuario_reputacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    score_reputacao INTEGER DEFAULT 0,
    nivel_reputacao VARCHAR(50),
    avaliacoes_util INTEGER DEFAULT 0,
    avaliacao_favoraveis INTEGER DEFAULT 0,
    avaliacao_negativas INTEGER DEFAULT 0,
    data_ultima_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id)
);


CREATE TABLE IF NOT EXISTS usuario_nivel (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    nivel_atual INTEGER DEFAULT 1,
    experiencia_atual INTEGER DEFAULT 0,
    experiencia_para_proximo_nivel INTEGER,
    beneficios_nivel JSONB,
    data_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id)
);


CREATE TABLE IF NOT EXISTS alerta_preco_ativado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    preco_limite NUMERIC(10, 2),
    tipo_alerta TEXT DEFAULT 'reducao' CHECK (tipo_alerta IN ('reducao', 'aumento', 'promocao')),
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, software_id)
);


CREATE TABLE IF NOT EXISTS historico_alerta_preco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alerta_id INTEGER NOT NULL,
    preco_anterior NUMERIC(10, 2),
    preco_novo NUMERIC(10, 2),
    data_alteracao TIMESTAMPTZ DEFAULT NOW(),
    usuario_notificado BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (alerta_id) REFERENCES alerta_preco_ativado(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS alerta_novo_produto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    categoria_monitorada VARCHAR(100),
    tags_monitoradas VARCHAR(500),
    fornecedor_monitorado INTEGER,
    notificar_email BOOLEAN DEFAULT TRUE,
    notificar_push BOOLEAN DEFAULT TRUE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (fornecedor_monitorado) REFERENCES fornecedores(id)
);


CREATE TABLE IF NOT EXISTS alerta_atualizacao_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    notificar_todas_atualizacoes BOOLEAN DEFAULT TRUE,
    notificar_security_patch BOOLEAN DEFAULT TRUE,
    notificar_feature_major BOOLEAN DEFAULT FALSE,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (usuario_id, software_id)
);


CREATE TABLE IF NOT EXISTS impressoes_produto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    usuario_id INTEGER,
    pagina_origem VARCHAR(500),
    posicao_listagem INTEGER,
    tipo_listagem VARCHAR(50),
    data_impressao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_data ON impressoes_produto(data_impressao);


CREATE TABLE IF NOT EXISTS cliques_cta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    usuario_id INTEGER,
    tipo_cta VARCHAR(100),
    posicao_cta VARCHAR(100),
    origem_pagina VARCHAR(500),
    data_clique TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS tempo_visualizacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    sessao_id VARCHAR(255),
    tempo_segundos INTEGER,
    data_visualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);


CREATE TABLE IF NOT EXISTS usuario_admin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    nivel_acesso TEXT CHECK (nivel_acesso IN ('super_admin', 'admin_conteudo', 'admin_financeiro', 'admin_suporte', 'moderador')) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    data_promocao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    UNIQUE (usuario_id)
);


CREATE TABLE IF NOT EXISTS permissoes_admin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    permissao VARCHAR(100) NOT NULL,
    recurso_alvo VARCHAR(100),
    data_concessao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (admin_id) REFERENCES usuario_admin(id) ON DELETE CASCADE,
    UNIQUE (admin_id, permissao, recurso_alvo)
);


CREATE TABLE IF NOT EXISTS acoes_admin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    tipo_acao VARCHAR(100) NOT NULL,
    alvo_acao VARCHAR(255),
    descricao TEXT,
    dados_anterior JSONB,
    dados_novo JSONB,
    resultado TEXT DEFAULT 'sucesso' CHECK (resultado IN ('sucesso', 'falha')),
    motivo_falha VARCHAR(255),
    data_acao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (admin_id) REFERENCES usuario_admin(id)
);
CREATE INDEX IF NOT EXISTS idx_tipo_acao ON acoes_admin(tipo_acao);
CREATE INDEX IF NOT EXISTS idx_data_acao ON acoes_admin(data_acao);


CREATE TABLE IF NOT EXISTS tickets_admin_marketplace (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    assunto VARCHAR(255),
    descricao TEXT,
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
    categoria VARCHAR(100),
    status TEXT DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_progresso', 'resolvido', 'fechado')),
    assignado_para INTEGER,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_resolucao DATE,
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (assignado_para) REFERENCES usuario_admin(id)
);


CREATE TABLE IF NOT EXISTS verificacao_qualidade_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    score_qualidade NUMERIC(3, 2),
    documentacao_score NUMERIC(3, 2),
    seguranca_score NUMERIC(3, 2),
    performance_score NUMERIC(3, 2),
    compatibilidade_score NUMERIC(3, 2),
    suporte_score NUMERIC(3, 2),
    recomendacoes TEXT,
    revisado_por INTEGER,
    data_analise TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (revisado_por) REFERENCES usuario_admin(id)
);


CREATE TABLE IF NOT EXISTS teste_compatibilidade (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    sistema_operacional VARCHAR(50),
    versao_testada VARCHAR(50),
    status_teste TEXT DEFAULT 'nao_testado' CHECK (status_teste IN ('sucesso', 'falha', 'parcial', 'nao_testado')),
    observacoes TEXT,
    data_teste TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id)
);


CREATE TABLE IF NOT EXISTS malware_scan_resultado (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    versao_software VARCHAR(50),
    mecanismo_scan VARCHAR(100),
    data_scan TIMESTAMPTZ DEFAULT NOW(),
    resultado TEXT DEFAULT 'limpo' CHECK (resultado IN ('limpo', 'suspeito', 'infectado')),
    deteccoes_encontradas INTEGER DEFAULT 0,
    detalhes_deteccoes JSONB,
    hash_arquivo VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS certificado_seguranca (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    tipo_certificado VARCHAR(100),
    numero_certificado VARCHAR(255),
    data_emissao DATE,
    data_expiracao DATE,
    autoridade_certificadora VARCHAR(255),
    certificado_arquivo VARCHAR(500)
);


CREATE TABLE IF NOT EXISTS tipo_distribuicao_software (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    tipo_distribuicao TEXT CHECK (tipo_distribuicao IN ('download', 'saas', 'cloud', 'api', 'plugin', 'extensao', 'hibrido')) NOT NULL,
    descricao VARCHAR(500),
    url_acesso VARCHAR(500),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id, tipo_distribuicao)
);


CREATE TABLE IF NOT EXISTS saas_configuracao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    software_id INTEGER NOT NULL,
    dominio_principal VARCHAR(255),
    infraestrutura VARCHAR(100),
    provedor_cloud TEXT DEFAULT 'aws' CHECK (provedor_cloud IN ('aws', 'azure', 'gcp', 'digitalocean', 'linode', 'outro')),
    regiao_padrao VARCHAR(100),
    database_tipo VARCHAR(50),
    cache_tipo VARCHAR(50),
    cdn_habilitado BOOLEAN DEFAULT TRUE,
    backup_automatico BOOLEAN DEFAULT TRUE,
    frequencia_backup VARCHAR(50) DEFAULT 'diaria',
    uptime_garantido NUMERIC(5, 2),
    support_level TEXT DEFAULT 'basic' CHECK (support_level IN ('community', 'basic', 'premium', 'enterprise')),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (software_id) REFERENCES softwares(id) ON DELETE CASCADE,
    UNIQUE (software_id)
);


CREATE TABLE IF NOT EXISTS saas_instancia_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licenca_id INTEGER NOT NULL,
    software_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    url_acesso VARCHAR(500),
    subdomain VARCHAR(255) UNIQUE,
    dominio_customizado VARCHAR(255) UNIQUE,
    status_instancia TEXT DEFAULT 'criando' CHECK (status_instancia IN ('criando', 'ativa', 'pausada', 'suspensa', 'deletada')),
    tipo_ambiente TEXT DEFAULT 'producao' CHECK (tipo_ambiente IN ('producao', 'staging', 'desenvolvimento')),
    versao_software VARCHAR(50),
    regiao_servidor VARCHAR(100),
    ip_servidor VARCHAR(50),
    servidor_origem VARCHAR(255),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_ativacao TIMESTAMPTZ,
    data_delecao TIMESTAMPTZ,
    FOREIGN KEY (licenca_id) REFERENCES licencas(id) ON DELETE CASCADE,
    FOREIGN KEY (software_id) REFERENCES softwares(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_usuario_software ON saas_instancia_usuario(usuario_id, software_id);
CREATE INDEX IF NOT EXISTS idx_status ON saas_instancia_usuario(status_instancia);


CREATE TABLE IF NOT EXISTS saas_acessos_instancia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    tipo_acesso TEXT DEFAULT 'admin' CHECK (tipo_acesso IN ('admin', 'usuario', 'desenvolvedor', 'suporte', 'leitura')),
    username VARCHAR(255),
    email_acesso VARCHAR(255),
    senha_hash VARCHAR(255),
    senha_temporaria BOOLEAN DEFAULT FALSE,
    data_criacao_acesso TIMESTAMPTZ DEFAULT NOW(),
    data_ultima_login TIMESTAMPTZ,
    ativo BOOLEAN DEFAULT TRUE,
    permissoes JSONB,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_username ON saas_acessos_instancia(username);


CREATE TABLE IF NOT EXISTS saas_limites_plano (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plano_id INTEGER NOT NULL,
    limite_usuarios INTEGER,
    limite_storage_gb INTEGER,
    limite_bandwidth_gb INTEGER,
    limite_api_chamadas_dia INTEGER,
    limite_usuarios_simultaneos INTEGER,
    limite_projetos INTEGER,
    limite_integrações INTEGER,
    limite_webhooks INTEGER,
    limite_agendamentos INTEGER,
    limite_execucoes_mes INTEGER,
    suporte_prioridade TEXT DEFAULT 'email' CHECK (suporte_prioridade IN ('email', 'chat', 'phone', 'dedicado')),
    tempo_resposta_horas INTEGER,
    sso_permitido BOOLEAN DEFAULT FALSE,
    whitelabel_permitido BOOLEAN DEFAULT FALSE,
    custom_domain_permitido BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (plano_id) REFERENCES planos_preco(id) ON DELETE CASCADE,
    UNIQUE (plano_id)
);


CREATE TABLE IF NOT EXISTS saas_consumo_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    mes_referencia DATE,
    storage_usado_gb NUMERIC(10, 2),
    bandwidth_usado_gb NUMERIC(10, 2),
    usuarios_ativos INTEGER,
    chamdas_api_mes INTEGER,
    requisicoes_webhook INTEGER,
    integrações_ativas INTEGER,
    tempo_uptime_percentual NUMERIC(5, 2),
    excesso_identificado BOOLEAN DEFAULT FALSE,
    data_calculo TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    UNIQUE (instancia_id, mes_referencia)
);
CREATE INDEX IF NOT EXISTS idx_data_calculo ON saas_consumo_usuario(data_calculo);


CREATE TABLE IF NOT EXISTS saas_health_check (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    endpoint_verificacao VARCHAR(500),
    status_resposta VARCHAR(50),
    tempo_resposta_ms INTEGER,
    codigo_http INTEGER,
    disponibilidade BOOLEAN,
    detalhes_erro TEXT,
    data_verificacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_instancia_data ON saas_health_check(instancia_id, data_verificacao);


CREATE TABLE IF NOT EXISTS saas_historico_uptime (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    data_relatorio DATE,
    percentual_uptime NUMERIC(5, 2),
    tempo_downtime_minutos INTEGER,
    incidentes_count INTEGER,
    alertas_count INTEGER,
    performance_score NUMERIC(3, 2),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    UNIQUE (instancia_id, data_relatorio)
);


CREATE TABLE IF NOT EXISTS saas_backup (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    tipo_backup TEXT DEFAULT 'incremental' CHECK (tipo_backup IN ('incremental', 'completo', 'diferencial')),
    tamanho_backup_gb NUMERIC(10, 2),
    local_armazenamento VARCHAR(255),
    data_backup TIMESTAMPTZ DEFAULT NOW(),
    data_proxima_restauracao DATE,
    status_backup TEXT DEFAULT 'em_progresso' CHECK (status_backup IN ('sucesso', 'em_progresso', 'falha')),
    tempo_restauracao_minutos INTEGER,
    checagem_integridade BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_data ON saas_backup(data_backup);


CREATE TABLE IF NOT EXISTS saas_restauracao_backup (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_id INTEGER NOT NULL,
    instancia_id INTEGER NOT NULL,
    solicitado_por INTEGER,
    motivo_restauracao VARCHAR(255),
    data_solicitacao TIMESTAMPTZ DEFAULT NOW(),
    data_inicio_restauracao TIMESTAMPTZ,
    data_conclusao TIMESTAMPTZ,
    status TEXT DEFAULT 'solicitado' CHECK (status IN ('solicitado', 'em_progresso', 'concluido', 'falha')),
    detalhes_falha TEXT,
    FOREIGN KEY (backup_id) REFERENCES saas_backup(id),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id),
    FOREIGN KEY (solicitado_por) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS saas_logs_acesso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    usuario_id INTEGER,
    email_usuario VARCHAR(255),
    ip_acesso VARCHAR(50),
    user_agent VARCHAR(500),
    tipo_acesso TEXT DEFAULT 'login' CHECK (tipo_acesso IN ('login', 'logout', 'api_call', 'webhook', 'integracao')),
    endpoint_acessado VARCHAR(500),
    metodo VARCHAR(10),
    codigo_resposta INTEGER,
    tempo_requisicao_ms INTEGER,
    bytes_enviados INTEGER,
    bytes_recebidos INTEGER,
    data_acesso TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_instancia_data ON saas_logs_acesso(instancia_id, data_acesso);
CREATE INDEX IF NOT EXISTS idx_tipo_acesso ON saas_logs_acesso(tipo_acesso);


CREATE TABLE IF NOT EXISTS saas_logs_erro (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    tipo_erro VARCHAR(100),
    mensagem_erro TEXT,
    stack_trace TEXT,
    url_requisicao VARCHAR(500),
    usuario_afetado INTEGER,
    severidade TEXT DEFAULT 'error' CHECK (severidade IN ('info', 'warning', 'error', 'critical')),
    resolvido BOOLEAN DEFAULT FALSE,
    data_erro TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id),
    FOREIGN KEY (usuario_afetado) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_instancia_data ON saas_logs_erro(instancia_id, data_erro);
CREATE INDEX IF NOT EXISTS idx_severidade ON saas_logs_erro(severidade);


CREATE TABLE IF NOT EXISTS saas_atividades_instancia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    tipo_atividade VARCHAR(100),
    descricao TEXT,
    usuario_id INTEGER,
    dados_atividade JSONB,
    resultado TEXT DEFAULT 'sucesso' CHECK (resultado IN ('sucesso', 'falha', 'pendente')),
    data_atividade TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX IF NOT EXISTS idx_data ON saas_atividades_instancia(data_atividade);


CREATE TABLE IF NOT EXISTS saas_integracao_instancia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    software_integrado_id INTEGER,
    nome_integracao VARCHAR(255),
    tipo_integracao TEXT DEFAULT 'api' CHECK (tipo_integracao IN ('webhook', 'api', 'plugin', 'extensao', 'custom')),
    status_integracao TEXT DEFAULT 'ativa' CHECK (status_integracao IN ('ativa', 'inativa', 'erro')),
    chave_api_integracao VARCHAR(255),
    secret_integracao VARCHAR(255),
    configuracoes JSONB,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    ultima_sincronia TIMESTAMPTZ,
    proxima_sincronia TIMESTAMPTZ,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (software_integrado_id) REFERENCES softwares(id),
    UNIQUE (instancia_id, nome_integracao)
);


CREATE TABLE IF NOT EXISTS saas_webhooks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    url_webhook VARCHAR(500),
    eventos_disparadores JSONB,
    headers_customizados JSONB,
    metodo_http VARCHAR(10) DEFAULT 'POST',
    timeout_segundos INTEGER DEFAULT 30,
    tentativas_maximas INTEGER DEFAULT 3,
    tentativas_falhadas INTEGER DEFAULT 0,
    ultima_tentativa TIMESTAMPTZ,
    ativo BOOLEAN DEFAULT TRUE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ativo ON saas_webhooks(ativo);


CREATE TABLE IF NOT EXISTS saas_webhook_chamadas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id INTEGER NOT NULL,
    dados_enviados JSONB,
    resposta_recebida JSONB,
    codigo_resposta INTEGER,
    tempo_resposta_ms INTEGER,
    status_chamada TEXT DEFAULT 'sucesso' CHECK (status_chamada IN ('sucesso', 'falha', 'timeout')),
    tentativa_numero INTEGER,
    data_chamada TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (webhook_id) REFERENCES saas_webhooks(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_data ON saas_webhook_chamadas(data_chamada);


CREATE TABLE IF NOT EXISTS saas_configuracoes_instancia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    chave_config VARCHAR(100),
    valor_config TEXT,
    tipo TEXT DEFAULT 'string' CHECK (tipo IN ('string', 'number', 'BOOLEAN', 'JSONB', 'file')),
    data_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    UNIQUE (instancia_id, chave_config)
);


CREATE TABLE IF NOT EXISTS saas_branding_instancia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    logo_url VARCHAR(500),
    logo_favicon VARCHAR(500),
    cor_primaria VARCHAR(7),
    cor_secundaria VARCHAR(7),
    font_primaria VARCHAR(100),
    footer_customizado TEXT,
    header_customizado TEXT,
    css_custom TEXT,
    nome_brandizado VARCHAR(255),
    email_suporte_customizado VARCHAR(255),
    telefone_suporte VARCHAR(15),
    data_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS saas_certificado_ssl (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    dominio_certificado VARCHAR(255),
    tipo_certificado TEXT DEFAULT 'lets_encrypt' CHECK (tipo_certificado IN ('self_signed', 'lets_encrypt', 'comodo', 'custom')),
    data_emissao DATE,
    data_expiracao DATE,
    issuer VARCHAR(255),
    status_certificado TEXT DEFAULT 'valido' CHECK (status_certificado IN ('valido', 'proximo_expirar', 'expirado')),
    renov_automatica BOOLEAN DEFAULT TRUE,
    data_renovacao_proxima DATE,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    UNIQUE (instancia_id, dominio_certificado)
);


CREATE TABLE IF NOT EXISTS saas_recursos_alocados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    cpu_cores NUMERIC(3, 1),
    memoria_ram_gb INTEGER,
    storage_disco_gb INTEGER,
    bandwidth_limitado_gb INTEGER,
    conexoes_db_simultaneas INTEGER,
    conexoes_cache_simultaneas INTEGER,
    tipo_instancia VARCHAR(100),
    hardware_dedicado BOOLEAN DEFAULT FALSE,
    data_alocacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS saas_auto_scaling (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    auto_scaling_habilitado BOOLEAN DEFAULT FALSE,
    cpu_min_percentual INTEGER DEFAULT 30,
    cpu_max_percentual INTEGER DEFAULT 80,
    memoria_min_percentual INTEGER DEFAULT 30,
    memoria_max_percentual INTEGER DEFAULT 80,
    instâncias_minimas INTEGER DEFAULT 1,
    instâncias_maximas INTEGER DEFAULT 5,
    tempo_escala_minutos INTEGER DEFAULT 5,
    data_config TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS saas_metricas_tempo_real (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    timestamp_metrica TIMESTAMPTZ DEFAULT NOW(),
    cpu_percentual NUMERIC(5, 2),
    memoria_percentual NUMERIC(5, 2),
    disco_percentual NUMERIC(5, 2),
    latencia_ms INTEGER,
    requisicoes_por_segundo INTEGER,
    usuarios_conectados INTEGER,
    taxas_erro NUMERIC(5, 2),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_instancia_timestamp ON saas_metricas_tempo_real(instancia_id, timestamp_metrica);


CREATE TABLE IF NOT EXISTS saas_mudanca_plano (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licenca_id INTEGER NOT NULL,
    plano_anterior_id INTEGER,
    plano_novo_id INTEGER,
    data_mudanca TIMESTAMPTZ DEFAULT NOW(),
    data_efetivacao DATE,
    motivo_mudanca VARCHAR(255),
    prec_ajuste NUMERIC(10, 2),
    tipo_mudanca TEXT DEFAULT 'upgrade' CHECK (tipo_mudanca IN ('upgrade', 'downgrade', 'lateral')),
    status_mudanca TEXT DEFAULT 'solicitada' CHECK (status_mudanca IN ('solicitada', 'processando', 'efetiva', 'cancelada')),
    FOREIGN KEY (licenca_id) REFERENCES licencas(id),
    FOREIGN KEY (plano_anterior_id) REFERENCES planos_preco(id),
    FOREIGN KEY (plano_novo_id) REFERENCES planos_preco(id)
);


CREATE TABLE IF NOT EXISTS saas_alertas_saude (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    tipo_alerta TEXT CHECK (tipo_alerta IN ('high_cpu', 'high_memory', 'low_storage', 'downtime', 'error_rate', 'slow_response')) NOT NULL,
    severity TEXT DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'critical')),
    descricao TEXT,
    valor_atual NUMERIC(10, 2),
    valor_limite NUMERIC(10, 2),
    status_alerta TEXT DEFAULT 'ativo' CHECK (status_alerta IN ('ativo', 'resolvido', 'ignorado')),
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_resolucao TIMESTAMPTZ,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_status ON saas_alertas_saude(status_alerta);


CREATE TABLE IF NOT EXISTS saas_configuracao_alertas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    notificar_email BOOLEAN DEFAULT TRUE,
    notificar_sms BOOLEAN DEFAULT FALSE,
    notificar_slack BOOLEAN DEFAULT FALSE,
    notificar_pagerduty BOOLEAN DEFAULT FALSE,
    threshold_cpu INTEGER DEFAULT 80,
    threshold_memoria INTEGER DEFAULT 80,
    threshold_disco INTEGER DEFAULT 90,
    threshold_latencia_ms INTEGER DEFAULT 1000,
    threshold_taxa_erro NUMERIC(5, 2) DEFAULT 5.00,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    UNIQUE (instancia_id)
);


CREATE TABLE IF NOT EXISTS saas_tickets_suporte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    titulo VARCHAR(255),
    descricao TEXT,
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
    categoria VARCHAR(100),
    status TEXT DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_progresso', 'aguardando_cliente', 'resolvido', 'fechado')),
    tempo_resposta_primeira_msg INTEGER,
    tempo_resolucao INTEGER,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    data_resolucao DATE,
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);


CREATE TABLE IF NOT EXISTS saas_manutencao_agendada (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instancia_id INTEGER,
    data_inicio TIMESTAMPTZ,
    data_fim TIMESTAMPTZ,
    descricao TEXT,
    tipo_manutencao TEXT DEFAULT 'atualizacao' CHECK (tipo_manutencao IN ('atualizacao', 'patch_seguranca', 'migracao', 'otimizacao', 'outra')),
    impacto_esperado VARCHAR(255),
    notificacao_enviada BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (instancia_id) REFERENCES saas_instancia_usuario(id)
);
