SET search_path = public;

CREATE OR REPLACE FUNCTION fn_atualizar_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.data_atualizacao = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TYPE tipo_usuario AS ENUM ('cliente', 'empresa', 'freelancer');
CREATE TYPE tipo_servico AS ENUM ('servico', 'produto');
CREATE TYPE status_contrato AS ENUM ('pendente', 'aceito', 'em_andamento', 'concluido', 'cancelado');

CREATE TABLE usuarios (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo tipo_usuario NOT NULL,
    telefone VARCHAR(20),
    endereco TEXT,
    cidade VARCHAR(100),
    estado VARCHAR(50),
    cep VARCHAR(10),
    data_nascimento DATE,
    cpf_cnpj VARCHAR(20),
    descricao TEXT,
    foto_perfil VARCHAR(500),
    ativo BOOLEAN DEFAULT TRUE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nome_fantasia VARCHAR(255),
    razao_social VARCHAR(255),
    area_atuacao VARCHAR(255),
    especialidades JSONB,
    portfolio_url VARCHAR(500),
    site_url VARCHAR(500)
);

CREATE TABLE categorias (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    icone VARCHAR(100),
    ativo BOOLEAN DEFAULT TRUE,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servicos (
    id_servico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    categoria_id INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    tipo tipo_servico NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    prazo_entrega INT,
    imagens JSONB,
    tags JSONB,
    ativo BOOLEAN DEFAULT TRUE,
    destaque BOOLEAN DEFAULT FALSE,
    visualizacoes INT DEFAULT 0,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    busca_tsvector TSVECTOR GENERATED ALWAYS AS (to_tsvector('portuguese', COALESCE(titulo, '') || ' ' || COALESCE(descricao, ''))) STORED,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id_categoria) ON DELETE RESTRICT
);

CREATE TABLE avaliacoes (
    id_avaliacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_id INT NOT NULL,
    usuario_avaliador_id INT NOT NULL,
    usuario_avaliado_id INT NOT NULL,
    nota INT NOT NULL CHECK (nota >= 1 AND nota <= 5),
    comentario TEXT,
    data_avaliacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (servico_id) REFERENCES servicos(id_servico) ON DELETE CASCADE,
    FOREIGN KEY (usuario_avaliador_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (usuario_avaliado_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    UNIQUE (servico_id, usuario_avaliador_id)
);

CREATE TABLE mensagens (
    id_mensagem INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remetente_id INT NOT NULL,
    destinatario_id INT NOT NULL,
    servico_id INT,
    assunto VARCHAR(255),
    mensagem TEXT NOT NULL,
    lida BOOLEAN DEFAULT FALSE,
    data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (remetente_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (destinatario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (servico_id) REFERENCES servicos(id_servico) ON DELETE SET NULL
);

CREATE TABLE contratos (
    id_contrato INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_id INT NOT NULL,
    cliente_id INT NOT NULL,
    prestador_id INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    valor DECIMAL(10,2) NOT NULL,
    prazo_entrega DATE,
    status status_contrato DEFAULT 'pendente',
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_aceite TIMESTAMP NULL,
    data_conclusao TIMESTAMP NULL,
    data_cancelamento TIMESTAMP NULL,
    motivo_cancelamento TEXT,
    FOREIGN KEY (servico_id) REFERENCES servicos(id_servico) ON DELETE RESTRICT,
    FOREIGN KEY (cliente_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    FOREIGN KEY (prestador_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT
);

CREATE TABLE favoritos (
    id_favorito INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    servico_id INT NOT NULL,
    data_favoritado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (servico_id) REFERENCES servicos(id_servico) ON DELETE CASCADE,
    UNIQUE (usuario_id, servico_id)
);

CREATE TRIGGER tr_usuarios_atualizacao
BEFORE UPDATE ON usuarios
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_timestamp();

CREATE TRIGGER tr_servicos_atualizacao
BEFORE UPDATE ON servicos
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_timestamp();

INSERT INTO categorias (nome, descricao, icone) VALUES
('Design', 'Serviços de design gráfico, logos, identidade visual', 'design'),
('Programação', 'Desenvolvimento de sites, aplicativos e sistemas', 'code'),
('Marketing', 'Marketing digital, gestão de redes sociais, SEO', 'marketing'),
('Redação', 'Criação de conteúdo, copywriting, tradução', 'edit'),
('Fotografia', 'Fotografia profissional, edição de imagens', 'camera'),
('Vídeo', 'Produção e edição de vídeos, motion graphics', 'video'),
('Música', 'Produção musical, trilhas sonoras, locução', 'music'),
('Consultoria', 'Consultoria empresarial, financeira, jurídica', 'business'),
('Educação', 'Aulas particulares, cursos online, treinamentos', 'education'),
('Comércio', 'Produtos físicos, artesanato, vendas', 'shopping');

INSERT INTO usuarios (nome, email, senha, tipo, descricao) VALUES
('Administrador DevHub', 'admin@summit.com', 'admin123', 'empresa', 'Conta administrativa da plataforma DevHub');

CREATE OR REPLACE VIEW vw_estatisticas_usuarios AS
SELECT 
    tipo,
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE ativo = TRUE) as ativos,
    COUNT(*) FILTER (WHERE DATE(data_cadastro) = CURRENT_DATE) as novos_hoje,
    COUNT(*) FILTER (WHERE data_cadastro >= (CURRENT_DATE - INTERVAL '7 day')) as novos_semana
FROM usuarios
GROUP BY tipo;

CREATE OR REPLACE VIEW vw_servicos_completos AS
SELECT 
    s.*,
    u.nome as nome_usuario,
    u.foto_perfil as foto_usuario,
    c.nome as nome_categoria,
    c.icone as icone_categoria,
    COALESCE(AVG(a.nota), 0) as media_avaliacoes,
    COUNT(a.id_avaliacao) as total_avaliacoes
FROM servicos s
JOIN usuarios u ON s.usuario_id = u.id_usuario
JOIN categorias c ON s.categoria_id = c.id_categoria
LEFT JOIN avaliacoes a ON s.id_servico = a.servico_id
WHERE s.ativo = TRUE AND u.ativo = TRUE
GROUP BY s.id_servico, u.id_usuario, c.id_categoria;

CREATE OR REPLACE VIEW vw_ranking_prestadores AS
SELECT 
    u.id_usuario,
    u.nome,
    u.foto_perfil,
    u.tipo,
    COUNT(s.id_servico) as total_servicos,
    COALESCE(AVG(a.nota), 0) as media_avaliacoes,
    COUNT(a.id_avaliacao) as total_avaliacoes,
    COUNT(c.id_contrato) as contratos_concluidos
FROM usuarios u
LEFT JOIN servicos s ON u.id_usuario = s.usuario_id AND s.ativo = TRUE
LEFT JOIN avaliacoes a ON u.id_usuario = a.usuario_avaliado_id
LEFT JOIN contratos c ON u.id_usuario = c.prestador_id AND c.status = 'concluido'
WHERE u.tipo IN ('freelancer', 'empresa') AND u.ativo = TRUE
GROUP BY u.id_usuario
HAVING COUNT(s.id_servico) > 0
ORDER BY media_avaliacoes DESC, total_avaliacoes DESC;

CREATE OR REPLACE FUNCTION fn_incrementar_visualizacoes()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.servico_id IS NOT NULL THEN
        UPDATE servicos
        SET visualizacoes = visualizacoes + 1
        WHERE id_servico = NEW.servico_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_incrementar_visualizacoes
AFTER INSERT ON mensagens
FOR EACH ROW
EXECUTE FUNCTION fn_incrementar_visualizacoes();

CREATE OR REPLACE FUNCTION BuscarServicos(
    p_termo VARCHAR(255),
    p_id_categoria INT,
    p_tipo VARCHAR(20),
    p_preco_min DECIMAL(10,2),
    p_preco_max DECIMAL(10,2),
    p_limite INT,
    p_offset INT
)
RETURNS SETOF vw_servicos_completos AS $$
BEGIN
    RETURN QUERY
    SELECT * FROM vw_servicos_completos
    WHERE 
        (p_termo IS NULL OR busca_tsvector @@ plainto_tsquery('portuguese', p_termo))
        AND (p_id_categoria IS NULL OR id_categoria = p_id_categoria)
        AND (p_tipo IS NULL OR vw_servicos_completos.tipo = p_tipo::tipo_servico)
        AND (p_preco_min IS NULL OR preco >= p_preco_min)
        AND (p_preco_max IS NULL OR preco <= p_preco_max)
    ORDER BY data_cadastro DESC
    LIMIT p_limite OFFSET p_offset;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION EstatisticasUsuario(p_usuario_id INT)
RETURNS TABLE(
    nome VARCHAR(255),
    tipo tipo_usuario,
    area_atuacao VARCHAR(255),
    especialidades JSONB,
    portfolio_url VARCHAR(500),
    site_url VARCHAR(500),
    total_servicos BIGINT,
    servicos_ativos BIGINT,
    media_avaliacoes DECIMAL,
    total_avaliacoes BIGINT,
    total_contratos BIGINT,
    contratos_concluidos BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u.nome,
        u.tipo,
        u.area_atuacao,
        u.especialidades,
        u.portfolio_url,
        u.site_url,
        COUNT(s.id_servico) as total_servicos,
        COUNT(s.id_servico) FILTER (WHERE s.ativo = TRUE) as servicos_ativos,
        COALESCE(AVG(a.nota), 0::DECIMAL) as media_avaliacoes,
        COUNT(a.id_avaliacao) as total_avaliacoes,
        COUNT(c.id_contrato) as total_contratos,
        COUNT(c.id_contrato) FILTER (WHERE c.status = 'concluido') as contratos_concluidos
    FROM usuarios u
    LEFT JOIN servicos s ON u.id_usuario = s.usuario_id
    LEFT JOIN avaliacoes a ON u.id_usuario = a.usuario_avaliado_id
    LEFT JOIN contratos c ON u.id_usuario = c.prestador_id
    WHERE u.id_usuario = p_usuario_id
    GROUP BY u.id_usuario;
END;
$$ LANGUAGE plpgsql;

CREATE INDEX IF NOT EXISTS idx_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_tipo ON usuarios(tipo);
CREATE INDEX IF NOT EXISTS idx_ativo ON usuarios(ativo);
CREATE INDEX IF NOT EXISTS idx_data_cadastro ON usuarios(data_cadastro);
CREATE INDEX IF NOT EXISTS idx_nome ON categorias(nome);
CREATE INDEX IF NOT EXISTS idx_ativo_cat ON categorias(ativo);
CREATE INDEX IF NOT EXISTS idx_usuario_id ON servicos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_categoria_id ON servicos(categoria_id);
CREATE INDEX IF NOT EXISTS idx_tipo_serv ON servicos(tipo);
CREATE INDEX IF NOT EXISTS idx_ativo_serv ON servicos(ativo);
CREATE INDEX IF NOT EXISTS idx_destaque ON servicos(destaque);
CREATE INDEX IF NOT EXISTS idx_preco ON servicos(preco);
CREATE INDEX IF NOT EXISTS idx_data_cadastro_serv ON servicos(data_cadastro);
CREATE INDEX IF NOT EXISTS idx_servicos_busca_tsvector ON servicos USING GIN(busca_tsvector);
CREATE INDEX IF NOT EXISTS idx_servico_id_aval ON avaliacoes(servico_id);
CREATE INDEX IF NOT EXISTS idx_usuario_avaliador ON avaliacoes(usuario_avaliador_id);
CREATE INDEX IF NOT EXISTS idx_usuario_avaliado ON avaliacoes(usuario_avaliado_id);
CREATE INDEX IF NOT EXISTS idx_nota ON avaliacoes(nota);
CREATE INDEX IF NOT EXISTS idx_data_avaliacao ON avaliacoes(data_avaliacao);
CREATE INDEX IF NOT EXISTS idx_remetente ON mensagens(remetente_id);
CREATE INDEX IF NOT EXISTS idx_destinatario ON mensagens(destinatario_id);
CREATE INDEX IF NOT EXISTS idx_servico_msg ON mensagens(servico_id);
CREATE INDEX IF NOT EXISTS idx_lida ON mensagens(lida);
CREATE INDEX IF NOT EXISTS idx_data_envio ON mensagens(data_envio);
CREATE INDEX IF NOT EXISTS idx_servico_id_cont ON contratos(servico_id);
CREATE INDEX IF NOT EXISTS idx_cliente_id ON contratos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_prestador_id ON contratos(prestador_id);
CREATE INDEX IF NOT EXISTS idx_status ON contratos(status);
CREATE INDEX IF NOT EXISTS idx_data_criacao ON contratos(data_criacao);
CREATE INDEX IF NOT EXISTS idx_usuario_id_fav ON favoritos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_servico_id_fav ON favoritos(servico_id);
CREATE INDEX IF NOT EXISTS idx_data_favoritado ON favoritos(data_favoritado);
CREATE INDEX IF NOT EXISTS idx_servicos_categoria_tipo ON servicos(categoria_id, tipo, ativo);
CREATE INDEX IF NOT EXISTS idx_servicos_usuario_ativo ON servicos(usuario_id, ativo);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_usuario_nota ON avaliacoes(usuario_avaliado_id, nota);
CREATE INDEX IF NOT EXISTS idx_contratos_status_data ON contratos(status, data_criacao);

DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'devhub_app') THEN
      CREATE ROLE devhub_app LOGIN PASSWORD '12345';
   END IF;
END
$do$;

GRANT CONNECT ON DATABASE postgres TO devhub_app;
GRANT USAGE ON SCHEMA public TO devhub_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO devhub_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO devhub_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO devhub_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO devhub_app;